version: '3.1'

services:

  mongo1:
    build:
      dockerfile: mongo1.Dockerfile
    restart: always
    container_name: Mongo1_Container
    hostname: mongo1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: python
      MONGO_INITDB_ROOT_PASSWORD: python
    volumes:
      - mongo1_data:/data/config

  redis:
    image: redis/redis-stack-server
    restart: always
    container_name: Redis_Container
    ports:
      - "6379:6379"
      - "8001:8001"

  nginx:
    image: nginx:latest
    restart: always
    container_name: Nginx_Container
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - mongo1
      - redis

volumes:
  mongo1_data:
  mongo2_data:

